### ISSUE TITLE
Add color picker to channel settings

### ISSUE THREAD

**Issue by tvb** [esotalk/esoTalk#371]
I think we have discussed this before but it shouldn't be to hard to implement a color picker which generates the following css styling:

``` css
.channel.channel-1 {
    border-color: #354059 !important;
    color: #354059 !important;
}
.tabs li a.channel-1:hover {
    border-color: #354059 !important;
    color: #354059 !important;
}
```
